# Generated by Django 3.2.8 on 2021-11-12 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartMent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': '部门管理',
                'db_table': 'tb_dep',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('age', models.PositiveSmallIntegerField()),
                ('salary', models.PositiveIntegerField()),
                ('avatar', models.ImageField(blank=True, upload_to='avatar/%Y%m%d')),
                ('birthday', models.DateField()),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.department')),
            ],
            options={
                'verbose_name_plural': '员工管理',
                'db_table': 'tb_staff',
            },
        ),
    ]
