# Generated by Django 3.2.8 on 2021-11-12 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_department_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='username',
            new_name='staff_name',
        ),
    ]
