# Generated by Django 3.2.8 on 2021-11-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_username_staff_staff_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='gender',
            field=models.IntegerField(choices=[(0, '男'), (1, '女')], default=1),
            preserve_default=False,
        ),
    ]
